# Generated by Django 3.0 on 2019-12-21 17:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencer_account', models.CharField(max_length=30)),
                ('influencer_platform', models.CharField(choices=[('IN', 'Instagram'), ('FA', 'Facebook'), ('TW', 'Twitter')], default='IN', max_length=2)),
                ('basics', django.contrib.postgres.fields.jsonb.JSONField()),
                ('earnings', django.contrib.postgres.fields.jsonb.JSONField()),
                ('interests', django.contrib.postgres.fields.jsonb.JSONField()),
                ('locations', django.contrib.postgres.fields.jsonb.JSONField()),
                ('personality_traits', django.contrib.postgres.fields.jsonb.JSONField()),
                ('engagements', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sentiments', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
