# Generated by Django 3.0 on 2019-12-23 18:00

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('brand_category', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=None), size=None)),
                ('brand_comptetitors', models.CharField(max_length=255)),
                ('brand_attributes', models.CharField(max_length=255)),
                ('key_selling_point', models.CharField(max_length=255)),
                ('age_range', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None), size=None)),
                ('social_status', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=None), size=None)),
                ('interests', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=None), size=None)),
                ('personality', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
                ('location', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=None), size=None)),
                ('touchpoint', models.CharField(max_length=255)),
                ('campaign_brief', models.TextField(max_length=4000)),
                ('campaign_budget', models.IntegerField()),
                ('campaign_currency', models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR')], default='usd', max_length=3)),
                ('campaign_kpis', models.CharField(max_length=64)),
                ('active_social_media', models.CharField(max_length=64)),
                ('previous_marketing_campaigns', models.CharField(max_length=64)),
                ('owned_event', models.CharField(max_length=64)),
                ('sponsored_event', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
