# Generated by Django 3.0 on 2019-12-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='brand_attributes',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_brief',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_kpis',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='key_selling_point',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='touchpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
