# Generated by Django 3.0 on 2020-01-16 01:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200113_1828'),
        ('campaign', '0003_auto_20200116_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_suggestion', models.CharField(blank=True, max_length=200, null=True)),
                ('contract_terms', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('contract_status', models.CharField(choices=[('OT', 'Opted'), ('DS', 'Discussing'), ('OF', 'Offered'), ('AC', 'Accepted'), ('RE', 'Rejected'), ('CA', 'Cancelled'), ('CO', 'Completed')], default='OT', max_length=2)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('influencer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Influencer')),
            ],
        ),
    ]
