# Generated by Django 3.0 on 2020-01-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_auto_20200123_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
