# Generated by Django 3.0 on 2020-01-27 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200113_1828'),
        ('campaign', '0006_contract_contract_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_status',
            field=models.CharField(choices=[('OF', 'Offered'), ('AC', 'Accepted'), ('PO', 'Posted'), ('DE', 'Declined'), ('CA', 'Cancelled'), ('CO', 'Completed')], default='OF', max_length=2),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('file_name', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.FileField(upload_to='%Y/%m/%d')),
                ('status', models.CharField(choices=[('CR', 'Waiting for approval'), ('AC', 'Accepted'), ('DE', 'Declined')], default='CR', max_length=2)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Contract')),
                ('upload_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Influencer')),
            ],
        ),
    ]
