# Generated by Django 3.0 on 2020-01-28 15:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_auto_20200127_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_posted', models.BooleanField(default=False, verbose_name='Status')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('analysis', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('post_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Media')),
            ],
        ),
    ]
