# Generated by Django 3.0 on 2020-02-07 16:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='active_social_media',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='age_range',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='brand_comptetitors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30, null=True), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='location',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30, null=True), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='owned_event',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='previous_marketing_campaigns',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='social_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='sponsored_event',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
