# Generated by Django 3.0 on 2020-02-07 16:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_auto_20200207_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='age_range',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='location',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='social_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=None), blank=True, null=True, size=None),
        ),
    ]
