# Generated by Django 3.0 on 2020-02-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_auto_20200207_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
