# Generated by Django 3.0 on 2020-02-11 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200113_1828'),
        ('campaign', '0012_post_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='influencer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Influencer'),
        ),
    ]
