# Generated by Django 3.0 on 2020-09-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0015_auto_20200212_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='chat_id',
            field=models.IntegerField(default=0, verbose_name='QB chat id'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='chat_login',
            field=models.CharField(default='', max_length=20),
        ),
    ]
