# Generated by Django 3.0 on 2019-12-26 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import invitation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0002_auto_20191223_1913'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('influencer', '0002_auto_20191223_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_key', models.CharField(default=invitation.models.generate_token, max_length=64)),
                ('influencer_account', models.CharField(max_length=30)),
                ('influencer_platform', models.CharField(choices=[('IN', 'Instagram'), ('FA', 'Facebook'), ('TW', 'Twitter')], default='IN', max_length=2)),
                ('invitation_content', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CR', 'CREATED'), ('SE', 'SENT'), ('AC', 'ACCEPTED'), ('RE', 'REJECTED'), ('CO', 'COMPLETED'), ('EX', 'EXPIRED')], default='CR', max_length=2)),
                ('analysis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='influencer.Analysis')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
