# Generated by Django 3.0 on 2019-12-18 17:32

from django.db import migrations, models
import invitation.models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('campaign_id', models.IntegerField()),
                ('invitation_key', models.CharField(default=invitation.models.generate_token, max_length=64)),
                ('influencer_account', models.CharField(max_length=30)),
                ('influencer_platform', models.CharField(choices=[('IN', 'Instagram'), ('FA', 'Facebook'), ('TW', 'Twitter'), ('LI', 'Linkedin')], default='IN', max_length=2)),
                ('invitation_content', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CR', 'CREATED'), ('SE', 'SENT'), ('AC', 'ACCEPTED'), ('RE', 'REJECTED'), ('CO', 'COMPLETED'), ('EX', 'EXPIRED')], default='CR', max_length=2)),
            ],
        ),
    ]
