# Generated by Django 3.0 on 2019-12-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('CR', 'CREATED'), ('SE', 'SENT'), ('AC', 'ACCEPTED'), ('RE', 'REJECTED'), ('CO', 'COMPLETED'), ('EX', 'EXPIRED'), ('CA', 'CANCELED')], default='CR', max_length=2),
        ),
    ]
