# Generated by Django 3.0 on 2019-12-24 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0002_auto_20191223_1913'),
        ('invitation', '0002_auto_20191224_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='campaign_id',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='client_id',
        ),
        migrations.AddField(
            model_name='invitation',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
