# Generated by Django 3.0 on 2019-12-24 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0002_auto_20191223_1340'),
        ('invitation', '0003_auto_20191224_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='analysis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='influencer.Analysis'),
        ),
    ]
