# Generated by Django 3.0 on 2019-12-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0004_invitation_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='influencer_account',
        ),
    ]
